### ISSUE TITLE
Release Demos URLs

### ISSUE THREAD

**Issue by Wandergarten** [streamlit/release-demos#21]
Hi there! 
I really appreciate the hard work you are putting into making streamlit as awesome as it is! 

I like that you create demo versions of release highlights on Streamlit community cloud! Unfortunately, I have not yet found a way to derive the correct (subdomain of the streamlit) URL of each version's demo, e.g. from release (folder) name or the demo's source code python file(s). Am I missing something? Is it possible to add release demo URLs to each release folder, e.g.

- Release './1.19.0/data_editor/': https://data-editor.streamlit.app/
- Release './1.18.0/columns_in_columns/': ??
- Release 1.16.0: 
     1. './demo_app_altair/': https://altair.streamlit.app/
     2. './demo_app_plotly/': https://plotly.streamlit.app/

This could either happen in [this repository's README.md](https://github.com/streamlit/release-demos/blob/master/README.md), [Github's release notes](https://github.com/streamlit/streamlit/releases), or the [official Streamlit Changelog in Docs](https://docs.streamlit.io/library/changelog). 

Cheers 🍺

**Comment by sfc-gh-tkipkemboi** [comment]
Thank you. We have updated the README with links to demo apps.
